server {
    listen 80;
    server_name info.adenchik.dev;

    root /usr/share/nginx/html;
    index index.html;

    # Скрываем версию nginx
    server_tokens off;

   # Запрет всех методов кроме GET и HEAD
    if ($request_method !~ ^(GET|HEAD)$ ) {
        return 405;
    }

    # Сначала запрещаем ВСЁ
    location / {
        deny all;
    }

    # Разрешаем только index.html
    location = / {
        try_files /index.html =404;
    }

    location = /index.html {
        allow all;
    }

    # Разрешаем style.css
    location = /style.css {
        allow all;
    }

    # Запрет скрытых файлов (.env, .git и т.д.)
    location ~ /\. {
        deny all;
    }

    # GZIP
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
    gzip_min_length 1000;

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Content-Security-Policy "default-src 'self'; img-src 'self' data: https:; script-src 'self' https: 'unsafe-inline'; style-src 'self' https: 'unsafe-inline';" always;

    # Кэширование статических файлов
    location ~* \.(jpg|jpeg|png|gif|ico|css|js|woff|woff2|ttf|svg)$ {
        expires 30d;
        access_log off;
    }
}