server {
    listen 80;
    server_name info.adenchik.dev;

    root /usr/share/nginx/html;
    index index.html;

    server_tokens off;

    # Только GET и HEAD
    if ($request_method !~ ^(GET|HEAD)$ ) {
        return 405;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    # Скрытые файлы
    location ~ /\. {
        deny all;
    }

    # GZIP
    gzip on;
    gzip_types text/plain text/css application/javascript application/json;
    gzip_min_length 1000;

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
}